### PR TITLE
A lot of missing methods was implemented including commands to control user, group, roles, acl etc

### PR DESCRIPTION
**Pull request by archer-v**
Hello, this is PR where a lot of missing methods was implemented :
 - Methods to control users, groups, roles, and acl commands (create, delete)
 - Method to create new FeatureType (for datastorages like postgress etc)
 - Method to create Postgis JNDI datastorage connection
 - DatastoreConnection struct was expanded with Options field allowing set additional datastorage options like "max connections", "Expose primary keys" etc 
 - Some broken tests were fixed or rewritten
 - Testing environment configuration was moved to .yml file

### CODE REVIEW

**Comment by hishamkaram** [comment]
Thank you for your contribution @mandalorian-one

**Comment by hishamkaram** [comment]
@mandalorian-one i fixed the pipeline but some unit test fails, could you check if you have time ?
https://app.travis-ci.com/github/hishamkaram/geoserver/jobs/549820810

**Comment by mandalorian-one** [comment]
Have no time now, but I have several improvements I planned to add more, I'll check these tests when I come back to this project

**Comment by hishamkaram** [comment]
Hey @archer-v — circling back five years later. 👋

The features you contributed in this PR (user/group/role/ACL commands, JNDI datastore, `DatastoreConnection.Options`, `CreateFeatureType`) have just been brought onto `master` as part of the v1.1 revival, in #37 (commit 6ff7320). They've been refactored to fit the current package idiom — every method comes with a `*Context` sibling, errors map to typed sentinels via `errors.Is`, and there's a parallel `*ServiceWithContext` interface for each new service — but the design is the same one you proposed:

- `SecurityService` covers `GetUsers`, `CreateUser`, `DeleteUser`, `GetGroups`, `CreateGroup`, `DeleteGroup`, `GetRoles`, `GetUserRoles`, `CreateRole`, `DeleteRole`, `AddUserRole`, `DeleteUserRole`.
- `ACLService` covers `GetLayersACLRules`, `AddLayersACLRule`, `DeleteLayersACLRule` with your `ACLRule` type and `ACLOpRead/Write/Admin` constants. (Renamed `Acl*` → `ACL*` to match Go's initialism convention; functionally identical.)
- `DatastoreConnector` interface + `DatastoreJNDIConnection` struct are in, with new methods `CreateJNDIDatastore` and `CreateDatastoreFromConnector`. The original `CreateDatastore(DatastoreConnection, ws)` signature is preserved for backward compatibility, so existing callers keep compiling.
- `DatastoreConnection.Options []Entry` is appended at the end of the struct (positional struct literals from v1.0 still compile).
- `CreateFeatureType` works against database-backed datastores — verified end-to-end against the seeded PostGIS table in our compose stack.

CI runs the integration matrix on every PR now (GeoServer 2.27.4 LTS + 2.28.0 stable), so the new code is exercised against both versions on every commit. One small bug came out of the port — `ParseURL` was double-encoding path segments containing `*` (your ACL rule strings were the trigger) — and got fixed in the same PR.

Thank you for the original work and patience. Sorry it took half a decade to get back to you!

**Pull request merged**
